// scripts/ai-core.js
// Central generation core. Default: offline/template-based.
// Optional: if user supplies OpenAI API key in settings, this module can forward requests to OpenAI (note: costs may apply).
// For zero-cost operation we use built-in templates (tools.js).

window.OmniAI = (function(){
  // check settings from local storage
  function getSettings(){
    try { return JSON.parse(localStorage.getItem('omniverse_settings')||'{}'); }
    catch { return {}; }
  }

  // Mock LLM call (deterministic + small random touches)
  function mockGenerate(text){
    // for safety: short transformation
    const suffixes = [
      " — Generated by Omniverse",
      " (AI-assisted draft)",
      " — Omniverse Marketplace",
      ""
    ];
    const pick = suffixes[Math.floor(Math.random()*suffixes.length)];
    return text + '\n\n' + pick;
  }

  // generate: uses tool.run; if premiumRequested and openaiKey present, optionally call actual API
  async function generate(tool, input = {}, opts = {}) {
    opts = opts || {};
    const settings = getSettings();
    const useOpenAI = settings.openaiKey && opts.forceOpenAI; // don't call by default
    if (useOpenAI) {
      // OPTIONAL: forward to OpenAI (developer/user must supply key in settings modal)
      // This branch is off by default for zero-cost operation.
      try {
        const resp = await fetch('https://api.openai.com/v1/chat/completions', {
          method:'POST',
          headers:{
            'Content-Type':'application/json',
            'Authorization':'Bearer ' + settings.openaiKey
          },
          body: JSON.stringify({
            model: "gpt-3.5-turbo",
            messages: [{role:'user', content: `Generate content for tool ${tool.id} using input ${JSON.stringify(input)}`}],
            max_tokens: 600
          })
        });
        const json = await resp.json();
        if (json && json.choices && json.choices[0]) {
          return json.choices[0].message.content;
        }
      } catch(e){
        console.warn('OpenAI call failed:', e);
        // fallback to template
      }
    }

    // Default: use tool's built-in run()
    try {
      const out = await tool.run(input, opts);
      return mockGenerate(out);
    } catch(e){
      return `Error generating: ${String(e)}`;
    }
  }

  return { generate, getSettings };
})();
