// scripts/ai-core.js
// Central generation core. Default: offline/template-based.
// Optional: if user supplies OpenAI API key in settings, this module can forward requests to OpenAI (note: costs may apply).
// For zero-cost operation we use built-in templates (tools.js).
window.OmniAI = (function(){
  function getSettings(){
    try { return JSON.parse(localStorage.getItem('omniverse_settings')||'{}'); } catch { return {}; }
  }
  function mockGenerate(text){
    const suffixes = [ " — Generated by Omniverse", " (AI-assisted draft)", " — Omniverse Marketplace", "" ];
    const pick = suffixes[Math.floor(Math.random()*suffixes.length)];
    return text + '\n\n' + pick;
  }
  async function generate(tool, input = {}, opts = {}) {
    opts = opts || {};
    const settings = getSettings();
    const useOpenAI = settings.openaiKey && opts.forceOpenAI;
    if (useOpenAI) {
      try {
        const resp = await fetch('https://api.openai.com/v1/chat/completions', {
          method:'POST',
          headers:{ 'Content-Type':'application/json', 'Authorization':'Bearer ' + settings.openaiKey },
          body: JSON.stringify({ model: "gpt-3.5-turbo", messages: [{role:'user', content: `Generate content for tool ${tool.id} using input ${JSON.stringify(input)}`}], max_tokens: 600 })
        });
        const json = await resp.json();
        if (json && json.choices && json.choices[0]) {
          return json.choices[0].message.content;
        }
      } catch(e){ console.warn('OpenAI call failed:', e); }
    }
    try {
      const out = await tool.run(input, opts);
      return mockGenerate(out);
    } catch(e){
      return `Error generating: ${String(e)}`;
    }
  }
  function getSettingsPublic(){ return getSettings(); }
  return { generate, getSettings: getSettingsPublic };
})();
