// scripts/tools.js
// Defines the list of tools and simple generation templates.
// Each tool.run(input, opts) returns a string result (Promise).
window.OmniTools = (function(){
  const tools = [
    {
      id: 'resume',
      name: 'Resume Generator',
      description: 'Generate a professional one-page resume.',
      premium: true,
      run: async (input, opts) => {
        const n = input.name || 'John Doe';
        const title = input.title || 'Software Engineer';
        const skills = input.skills || 'JavaScript, Python, Git';
        const summary = input.summary || `Result-driven ${title} with experience in building web apps.`;
        return [
          `${n}`,
          `${title}`,
          '',
          'Summary',
          summary,
          '',
          'Skills',
          skills.split(',').map(s=>s.trim()).join(', '),
          '',
          'Experience',
          input.experience || '- Company A (2020-2023): Worked on product features',
          '',
          'Education',
          input.education || 'B.Sc / M.Sc - Relevant University',
          '',
          'Generated by Omniverse AI Marketplace'
        ].join('\n');
      }
    },
    {
      id: 'bio',
      name: 'Bio Generator',
      description: 'Short personal or professional bios.',
      premium: false,
      run: async (input) => {
        const name = input.name || 'John Doe';
        const field = input.field || 'technology';
        const tone = input.tone || 'professional';
        const lines = [];
        lines.push(`${name} is a ${tone} ${field} professional who focuses on building practical solutions.`);
        lines.push(`Driven by curiosity and collaboration — interested in projects that scale.`);
        lines.push(`Contact: ${input.email || 'your.email@example.com'}`);
        lines.push('');
        lines.push('— Generated by Omniverse');
        return lines.join(' ');
      }
    },
    {
      id: 'script',
      name: 'Script Writer',
      description: 'Small JS / Python starter scripts.',
      premium: false,
      run: async (input) => {
        const lang = (input.lang || 'js').toLowerCase();
        const task = input.task || 'example task';
        if (lang === 'py' || lang === 'python') {
          return `# Python script — ${task}\n\ndef main():\n    print("Hello from Omniverse AI script generator")\n\nif __name__ == "__main__":\n    main()`;
        } else {
          return `// JS script — ${task}\nfunction main(){\n  console.log('Hello from Omniverse AI script generator');\n}\nmain();`;
        }
      }
    },
    {
      id: 'notes',
      name: 'Notes Generator',
      description: 'Meeting / study notes summarizer (template-based).',
      premium: false,
      run: async (input) => {
        const topic = input.topic || 'Untitled';
        const points = input.points || '1. Key idea\n2. Action items\n3. Next steps';
        return `Notes — ${topic}\n\n${points}\n\n— Generated by Omniverse`;
      }
    },
    {
      id: 'idea',
      name: 'Business Idea Generator',
      description: 'Quick startup / product ideas tuned to a field.',
      premium: true,
      run: async (input) => {
        const field = input.field || 'education';
        const core = `AI-powered ${field} assistant that automates repetitive tasks for small teams.`;
        const revenue = `Revenue model: subscription, freemium, marketplace take-rate.`;
        return `Idea — ${field}\n\nConcept: ${core}\n\nHow it helps: Reduce manual work and increase output.\n\n${revenue}\n\n— Omniverse`;
      }
    }
  ];
  function getList(){ return tools.map(t => ({id:t.id,name:t.name,description:t.description,premium:!!t.premium})); }
  function getTool(id){ return tools.find(t=>t.id===id); }
  return { getList, getTool };
})();
          
